"""added username

Revision ID: c60494f86d19
Revises: c5c23a835055
Create Date: 2024-05-21 20:36:02.123585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60494f86d19'
down_revision = 'c5c23a835055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
